// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Card.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Card.proto</summary>
public static partial class CardReflection {

  #region Descriptor
  /// <summary>File descriptor for Card.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CardReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpDYXJkLnByb3RvIjoKBENhcmQSGQoFcG9pbnQYASABKA4yCi5DYXJkUG9p",
          "bnQSFwoEc3VpdBgCIAEoDjIJLkNhcmRTdWl0KroBCglDYXJkUG9pbnQSDQoJ",
          "UG9pbnROb25lEAASCQoFVGhyZWUQAxIICgRGb3VyEAQSCAoERml2ZRAFEgcK",
          "A1NpeBAGEgkKBVNldmVuEAcSCQoFRWlnaHQQCBIICgROaW5lEAkSBwoDVGVu",
          "EAoSCAoESmFjaxALEgkKBVF1ZWVuEAwSCAoES2luZxANEgcKA09uZRAOEgcK",
          "A1R3bxAPEg4KCkpva2VyU21hbGwQEBIMCghKb2tlckJpZxARKkUKCENhcmRT",
          "dWl0EgwKCFN1aXROb25lEAASCwoHRGlhbW9uZBABEggKBENsdWIQAhIJCgVI",
          "ZWFydBADEgkKBVNwYWRlEAQqhQMKCENhcmRUeXBlEhAKDEhhbmRfVW5rbm93",
          "bhAAEg0KCUhhbmRfUGFzcxABEg8KC0hhbmRfU2luZ2xlEAISDQoJSGFuZF9Q",
          "YWlyEAMSDwoLSGFuZF9UcmlwbGUQBBIWChJIYW5kX1RyaXBsZV9TaW5nbGUQ",
          "BRIUChBIYW5kX1RyaXBsZV9QYWlyEAYSDgoKSGFuZF9QbGFuZRAHEhkKFUhh",
          "bmRfUGxhbmVfVHdvX1NpbmdsZRAIEhcKE0hhbmRfUGxhbmVfVHdvX1BhaXIQ",
          "CRIRCg1IYW5kX1NlcV9QYWlyEAoSEwoPSGFuZF9TZXFfU2luZ2xlEAsSDQoJ",
          "SGFuZF9Cb21iEAwSEgoOSGFuZF9Cb21iX1BhaXIQDRIYChRIYW5kX0JvbWJf",
          "VHdvX1NpbmdsZRAOEhQKEEhhbmRfQm9tYl9Kb2tlcnMQDxIZChVIYW5kX0Jv",
          "bWJfSm9rZXJzX1BhaXIQEBIfChtIYW5kX0JvbWJfSm9rZXJzX1R3b19TaW5n",
          "bGUQEWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CardPoint), typeof(global::CardSuit), typeof(global::CardType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Card), global::Card.Parser, new[]{ "Point", "Suit" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// 卡牌点数
/// </summary>
public enum CardPoint {
  [pbr::OriginalName("PointNone")] PointNone = 0,
  /// <summary>
  /// 3
  /// </summary>
  [pbr::OriginalName("Three")] Three = 3,
  /// <summary>
  /// 4
  /// </summary>
  [pbr::OriginalName("Four")] Four = 4,
  /// <summary>
  /// 5
  /// </summary>
  [pbr::OriginalName("Five")] Five = 5,
  /// <summary>
  /// 6
  /// </summary>
  [pbr::OriginalName("Six")] Six = 6,
  /// <summary>
  /// 7
  /// </summary>
  [pbr::OriginalName("Seven")] Seven = 7,
  /// <summary>
  /// 8
  /// </summary>
  [pbr::OriginalName("Eight")] Eight = 8,
  /// <summary>
  /// 9
  /// </summary>
  [pbr::OriginalName("Nine")] Nine = 9,
  /// <summary>
  /// 10
  /// </summary>
  [pbr::OriginalName("Ten")] Ten = 10,
  /// <summary>
  /// J
  /// </summary>
  [pbr::OriginalName("Jack")] Jack = 11,
  /// <summary>
  /// Q
  /// </summary>
  [pbr::OriginalName("Queen")] Queen = 12,
  /// <summary>
  /// K
  /// </summary>
  [pbr::OriginalName("King")] King = 13,
  /// <summary>
  /// A
  /// </summary>
  [pbr::OriginalName("One")] One = 14,
  /// <summary>
  /// 2
  /// </summary>
  [pbr::OriginalName("Two")] Two = 15,
  /// <summary>
  /// 小王
  /// </summary>
  [pbr::OriginalName("JokerSmall")] JokerSmall = 16,
  /// <summary>
  /// 大王
  /// </summary>
  [pbr::OriginalName("JokerBig")] JokerBig = 17,
}

/// <summary>
/// 卡牌花色
/// </summary>
public enum CardSuit {
  [pbr::OriginalName("SuitNone")] SuitNone = 0,
  /// <summary>
  /// 方块
  /// </summary>
  [pbr::OriginalName("Diamond")] Diamond = 1,
  /// <summary>
  /// 梅花
  /// </summary>
  [pbr::OriginalName("Club")] Club = 2,
  /// <summary>
  /// 红桃
  /// </summary>
  [pbr::OriginalName("Heart")] Heart = 3,
  /// <summary>
  /// 黑桃
  /// </summary>
  [pbr::OriginalName("Spade")] Spade = 4,
}

/// <summary>
/// 卡牌组合类型
/// </summary>
public enum CardType {
  /// <summary>
  /// 未知 or 非法
  /// </summary>
  [pbr::OriginalName("Hand_Unknown")] HandUnknown = 0,
  /// <summary>
  /// 过
  /// </summary>
  [pbr::OriginalName("Hand_Pass")] HandPass = 1,
  /// <summary>
  /// 单
  /// </summary>
  [pbr::OriginalName("Hand_Single")] HandSingle = 2,
  /// <summary>
  /// 对
  /// </summary>
  [pbr::OriginalName("Hand_Pair")] HandPair = 3,
  /// <summary>
  /// 三个
  /// </summary>
  [pbr::OriginalName("Hand_Triple")] HandTriple = 4,
  /// <summary>
  /// 三带一
  /// </summary>
  [pbr::OriginalName("Hand_Triple_Single")] HandTripleSingle = 5,
  /// <summary>
  /// 三带二
  /// </summary>
  [pbr::OriginalName("Hand_Triple_Pair")] HandTriplePair = 6,
  /// <summary>
  /// 飞机，555_666
  /// </summary>
  [pbr::OriginalName("Hand_Plane")] HandPlane = 7,
  /// <summary>
  /// 飞机带单，555_666_3_4
  /// </summary>
  [pbr::OriginalName("Hand_Plane_Two_Single")] HandPlaneTwoSingle = 8,
  /// <summary>
  /// 飞机带双，555_666_33_44
  /// </summary>
  [pbr::OriginalName("Hand_Plane_Two_Pair")] HandPlaneTwoPair = 9,
  /// <summary>
  /// 连对，33_44_55(_66...)
  /// </summary>
  [pbr::OriginalName("Hand_Seq_Pair")] HandSeqPair = 10,
  /// <summary>
  /// 顺子，34567(8...)
  /// </summary>
  [pbr::OriginalName("Hand_Seq_Single")] HandSeqSingle = 11,
  /// <summary>
  /// 炸弹
  /// </summary>
  [pbr::OriginalName("Hand_Bomb")] HandBomb = 12,
  /// <summary>
  /// 炸弹带一对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Pair")] HandBombPair = 13,
  /// <summary>
  /// 炸弹带两单
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Two_Single")] HandBombTwoSingle = 14,
  /// <summary>
  /// 王炸
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers")] HandBombJokers = 15,
  /// <summary>
  /// 王炸带一对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers_Pair")] HandBombJokersPair = 16,
  /// <summary>
  /// 王炸带两单
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers_Two_Single")] HandBombJokersTwoSingle = 17,
}

#endregion

#region Messages
/// <summary>
/// 卡牌
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Card : pb::IMessage<Card>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Card> _parser = new pb::MessageParser<Card>(() => new Card());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Card> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CardReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card(Card other) : this() {
    point_ = other.point_;
    suit_ = other.suit_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card Clone() {
    return new Card(this);
  }

  /// <summary>Field number for the "point" field.</summary>
  public const int PointFieldNumber = 1;
  private global::CardPoint point_ = global::CardPoint.PointNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CardPoint Point {
    get { return point_; }
    set {
      point_ = value;
    }
  }

  /// <summary>Field number for the "suit" field.</summary>
  public const int SuitFieldNumber = 2;
  private global::CardSuit suit_ = global::CardSuit.SuitNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CardSuit Suit {
    get { return suit_; }
    set {
      suit_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Card);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Card other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Point != other.Point) return false;
    if (Suit != other.Suit) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Point != global::CardPoint.PointNone) hash ^= Point.GetHashCode();
    if (Suit != global::CardSuit.SuitNone) hash ^= Suit.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Point != global::CardPoint.PointNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Suit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Point != global::CardPoint.PointNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Suit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Point != global::CardPoint.PointNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Suit);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Card other) {
    if (other == null) {
      return;
    }
    if (other.Point != global::CardPoint.PointNone) {
      Point = other.Point;
    }
    if (other.Suit != global::CardSuit.SuitNone) {
      Suit = other.Suit;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Point = (global::CardPoint) input.ReadEnum();
          break;
        }
        case 16: {
          Suit = (global::CardSuit) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Point = (global::CardPoint) input.ReadEnum();
          break;
        }
        case 16: {
          Suit = (global::CardSuit) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
