// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Card.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Card.proto</summary>
public static partial class CardReflection {

  #region Descriptor
  /// <summary>File descriptor for Card.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CardReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpDYXJkLnByb3RvIjoKBENhcmQSGQoFcG9pbnQYASABKA4yCi5DYXJkUG9p",
          "bnQSFwoEc3VpdBgCIAEoDjIJLkNhcmRTdWl0IlYKFERpc3BhdGNoQ2FyZFJl",
          "c3BvbnNlEhIKCmJhc2Vfc2NvcmUYASABKAUSEAoIbXVsdGlwbGUYAiABKAUS",
          "GAoJY2FyZF9saXN0GAMgAygLMgUuQ2FyZCJECgpQbGF5SGFuZEJvEgsKA3Bv",
          "cxgBIAEoBRIPCgdpc19wYXNzGAIgASgIEhgKCWNhcmRfbGlzdBgDIAMoCzIF",
          "LkNhcmQimQEKEFBsYXlIYW5kUmVzcG9uc2USEAoIbGFzdF9wb3MYASABKAUS",
          "DwoHaXNfcGFzcxgCIAEoCBIZCgpwZW5kX2NhcmRzGAMgAygLMgUuQ2FyZBIT",
          "Cgttb25zdGVyX3BvcxgEIAEoBRIQCghpc19jb3ZlchgFIAEoCBIOCgZpc19l",
          "bmQYBiABKAgSEAoIbXVsdGlwbGUYByABKAUqugEKCUNhcmRQb2ludBINCglQ",
          "b2ludE5vbmUQABIJCgVUaHJlZRADEggKBEZvdXIQBBIICgRGaXZlEAUSBwoD",
          "U2l4EAYSCQoFU2V2ZW4QBxIJCgVFaWdodBAIEggKBE5pbmUQCRIHCgNUZW4Q",
          "ChIICgRKYWNrEAsSCQoFUXVlZW4QDBIICgRLaW5nEA0SBwoDT25lEA4SBwoD",
          "VHdvEA8SDgoKSm9rZXJTbWFsbBAQEgwKCEpva2VyQmlnEBEqRQoIQ2FyZFN1",
          "aXQSDAoIU3VpdE5vbmUQABILCgdEaWFtb25kEAESCAoEQ2x1YhACEgkKBUhl",
          "YXJ0EAMSCQoFU3BhZGUQBCq0AwoIQ2FyZFR5cGUSEAoMSGFuZF9Vbmtub3du",
          "EAASDQoJSGFuZF9QYXNzEAESDwoLSGFuZF9TaW5nbGUQAhINCglIYW5kX1Bh",
          "aXIQAxIPCgtIYW5kX1RyaXBsZRAEEhYKEkhhbmRfVHJpcGxlX1NpbmdsZRAF",
          "EhQKEEhhbmRfVHJpcGxlX1BhaXIQBhIOCgpIYW5kX1BsYW5lEAcSFQoRSGFu",
          "ZF9QbGFuZV9TaW5nbGUQCBITCg9IYW5kX1BsYW5lX1BhaXIQCRIRCg1IYW5k",
          "X1NlcV9QYWlyEAoSEwoPSGFuZF9TZXFfU2luZ2xlEAsSDQoJSGFuZF9Cb21i",
          "EBUSEgoOSGFuZF9Cb21iX1BhaXIQDRIYChRIYW5kX0JvbWJfVHdvX1Npbmds",
          "ZRAOEhYKEkhhbmRfQm9tYl9Ud29fUGFpchAPEhQKEEhhbmRfQm9tYl9Kb2tl",
          "cnMQFhIZChVIYW5kX0JvbWJfSm9rZXJzX1BhaXIQERIfChtIYW5kX0JvbWJf",
          "Sm9rZXJzX1R3b19TaW5nbGUQEhIdChlIYW5kX0JvbWJfSm9rZXJzX1R3b19Q",
          "YWlyEBNiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CardPoint), typeof(global::CardSuit), typeof(global::CardType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Card), global::Card.Parser, new[]{ "Point", "Suit" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DispatchCardResponse), global::DispatchCardResponse.Parser, new[]{ "BaseScore", "Multiple", "CardList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayHandBo), global::PlayHandBo.Parser, new[]{ "Pos", "IsPass", "CardList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayHandResponse), global::PlayHandResponse.Parser, new[]{ "LastPos", "IsPass", "PendCards", "MonsterPos", "IsCover", "IsEnd", "Multiple" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// 卡牌点数
/// </summary>
public enum CardPoint {
  [pbr::OriginalName("PointNone")] PointNone = 0,
  /// <summary>
  /// 3
  /// </summary>
  [pbr::OriginalName("Three")] Three = 3,
  /// <summary>
  /// 4
  /// </summary>
  [pbr::OriginalName("Four")] Four = 4,
  /// <summary>
  /// 5
  /// </summary>
  [pbr::OriginalName("Five")] Five = 5,
  /// <summary>
  /// 6
  /// </summary>
  [pbr::OriginalName("Six")] Six = 6,
  /// <summary>
  /// 7
  /// </summary>
  [pbr::OriginalName("Seven")] Seven = 7,
  /// <summary>
  /// 8
  /// </summary>
  [pbr::OriginalName("Eight")] Eight = 8,
  /// <summary>
  /// 9
  /// </summary>
  [pbr::OriginalName("Nine")] Nine = 9,
  /// <summary>
  /// 10
  /// </summary>
  [pbr::OriginalName("Ten")] Ten = 10,
  /// <summary>
  /// J
  /// </summary>
  [pbr::OriginalName("Jack")] Jack = 11,
  /// <summary>
  /// Q
  /// </summary>
  [pbr::OriginalName("Queen")] Queen = 12,
  /// <summary>
  /// K
  /// </summary>
  [pbr::OriginalName("King")] King = 13,
  /// <summary>
  /// A
  /// </summary>
  [pbr::OriginalName("One")] One = 14,
  /// <summary>
  /// 2
  /// </summary>
  [pbr::OriginalName("Two")] Two = 15,
  /// <summary>
  /// 小王
  /// </summary>
  [pbr::OriginalName("JokerSmall")] JokerSmall = 16,
  /// <summary>
  /// 大王
  /// </summary>
  [pbr::OriginalName("JokerBig")] JokerBig = 17,
}

/// <summary>
/// 卡牌花色
/// </summary>
public enum CardSuit {
  [pbr::OriginalName("SuitNone")] SuitNone = 0,
  /// <summary>
  /// 方块
  /// </summary>
  [pbr::OriginalName("Diamond")] Diamond = 1,
  /// <summary>
  /// 梅花
  /// </summary>
  [pbr::OriginalName("Club")] Club = 2,
  /// <summary>
  /// 红桃
  /// </summary>
  [pbr::OriginalName("Heart")] Heart = 3,
  /// <summary>
  /// 黑桃
  /// </summary>
  [pbr::OriginalName("Spade")] Spade = 4,
}

/// <summary>
/// 卡牌组合类型
/// </summary>
public enum CardType {
  /// <summary>
  /// 未知 or 非法
  /// </summary>
  [pbr::OriginalName("Hand_Unknown")] HandUnknown = 0,
  /// <summary>
  /// 过
  /// </summary>
  [pbr::OriginalName("Hand_Pass")] HandPass = 1,
  /// <summary>
  /// 单
  /// </summary>
  [pbr::OriginalName("Hand_Single")] HandSingle = 2,
  /// <summary>
  /// 对
  /// </summary>
  [pbr::OriginalName("Hand_Pair")] HandPair = 3,
  /// <summary>
  /// 三个
  /// </summary>
  [pbr::OriginalName("Hand_Triple")] HandTriple = 4,
  /// <summary>
  /// 三带一
  /// </summary>
  [pbr::OriginalName("Hand_Triple_Single")] HandTripleSingle = 5,
  /// <summary>
  /// 三带二
  /// </summary>
  [pbr::OriginalName("Hand_Triple_Pair")] HandTriplePair = 6,
  /// <summary>
  /// 飞机，555_666
  /// </summary>
  [pbr::OriginalName("Hand_Plane")] HandPlane = 7,
  /// <summary>
  /// 飞机带单，555_666_3_4
  /// </summary>
  [pbr::OriginalName("Hand_Plane_Single")] HandPlaneSingle = 8,
  /// <summary>
  /// 飞机带双，555_666_33_44
  /// </summary>
  [pbr::OriginalName("Hand_Plane_Pair")] HandPlanePair = 9,
  /// <summary>
  /// 连对，33_44_55(_66...)
  /// </summary>
  [pbr::OriginalName("Hand_Seq_Pair")] HandSeqPair = 10,
  /// <summary>
  /// 顺子，34567(8...)
  /// </summary>
  [pbr::OriginalName("Hand_Seq_Single")] HandSeqSingle = 11,
  /// <summary>
  /// 炸弹
  /// </summary>
  [pbr::OriginalName("Hand_Bomb")] HandBomb = 21,
  /// <summary>
  /// 炸弹带一对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Pair")] HandBombPair = 13,
  /// <summary>
  /// 炸弹带两单
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Two_Single")] HandBombTwoSingle = 14,
  /// <summary>
  /// 炸弹带两对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Two_Pair")] HandBombTwoPair = 15,
  /// <summary>
  /// 王炸
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers")] HandBombJokers = 22,
  /// <summary>
  /// 王炸带一对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers_Pair")] HandBombJokersPair = 17,
  /// <summary>
  /// 王炸带两单
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers_Two_Single")] HandBombJokersTwoSingle = 18,
  /// <summary>
  /// 王炸带两对
  /// </summary>
  [pbr::OriginalName("Hand_Bomb_Jokers_Two_Pair")] HandBombJokersTwoPair = 19,
}

#endregion

#region Messages
/// <summary>
/// 卡牌
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Card : pb::IMessage<Card>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Card> _parser = new pb::MessageParser<Card>(() => new Card());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Card> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CardReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card(Card other) : this() {
    point_ = other.point_;
    suit_ = other.suit_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Card Clone() {
    return new Card(this);
  }

  /// <summary>Field number for the "point" field.</summary>
  public const int PointFieldNumber = 1;
  private global::CardPoint point_ = global::CardPoint.PointNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CardPoint Point {
    get { return point_; }
    set {
      point_ = value;
    }
  }

  /// <summary>Field number for the "suit" field.</summary>
  public const int SuitFieldNumber = 2;
  private global::CardSuit suit_ = global::CardSuit.SuitNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CardSuit Suit {
    get { return suit_; }
    set {
      suit_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Card);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Card other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Point != other.Point) return false;
    if (Suit != other.Suit) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Point != global::CardPoint.PointNone) hash ^= Point.GetHashCode();
    if (Suit != global::CardSuit.SuitNone) hash ^= Suit.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Point != global::CardPoint.PointNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Suit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Point != global::CardPoint.PointNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Suit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Point != global::CardPoint.PointNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Point);
    }
    if (Suit != global::CardSuit.SuitNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Suit);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Card other) {
    if (other == null) {
      return;
    }
    if (other.Point != global::CardPoint.PointNone) {
      Point = other.Point;
    }
    if (other.Suit != global::CardSuit.SuitNone) {
      Suit = other.Suit;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Point = (global::CardPoint) input.ReadEnum();
          break;
        }
        case 16: {
          Suit = (global::CardSuit) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Point = (global::CardPoint) input.ReadEnum();
          break;
        }
        case 16: {
          Suit = (global::CardSuit) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 发牌
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class DispatchCardResponse : pb::IMessage<DispatchCardResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DispatchCardResponse> _parser = new pb::MessageParser<DispatchCardResponse>(() => new DispatchCardResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DispatchCardResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CardReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DispatchCardResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DispatchCardResponse(DispatchCardResponse other) : this() {
    baseScore_ = other.baseScore_;
    multiple_ = other.multiple_;
    cardList_ = other.cardList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DispatchCardResponse Clone() {
    return new DispatchCardResponse(this);
  }

  /// <summary>Field number for the "base_score" field.</summary>
  public const int BaseScoreFieldNumber = 1;
  private int baseScore_;
  /// <summary>
  /// 底分
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BaseScore {
    get { return baseScore_; }
    set {
      baseScore_ = value;
    }
  }

  /// <summary>Field number for the "multiple" field.</summary>
  public const int MultipleFieldNumber = 2;
  private int multiple_;
  /// <summary>
  /// 加倍倍数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Multiple {
    get { return multiple_; }
    set {
      multiple_ = value;
    }
  }

  /// <summary>Field number for the "card_list" field.</summary>
  public const int CardListFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Card> _repeated_cardList_codec
      = pb::FieldCodec.ForMessage(26, global::Card.Parser);
  private readonly pbc::RepeatedField<global::Card> cardList_ = new pbc::RepeatedField<global::Card>();
  /// <summary>
  /// 分发的卡牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Card> CardList {
    get { return cardList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DispatchCardResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DispatchCardResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BaseScore != other.BaseScore) return false;
    if (Multiple != other.Multiple) return false;
    if(!cardList_.Equals(other.cardList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (BaseScore != 0) hash ^= BaseScore.GetHashCode();
    if (Multiple != 0) hash ^= Multiple.GetHashCode();
    hash ^= cardList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (BaseScore != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(BaseScore);
    }
    if (Multiple != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Multiple);
    }
    cardList_.WriteTo(output, _repeated_cardList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (BaseScore != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(BaseScore);
    }
    if (Multiple != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Multiple);
    }
    cardList_.WriteTo(ref output, _repeated_cardList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (BaseScore != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseScore);
    }
    if (Multiple != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Multiple);
    }
    size += cardList_.CalculateSize(_repeated_cardList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DispatchCardResponse other) {
    if (other == null) {
      return;
    }
    if (other.BaseScore != 0) {
      BaseScore = other.BaseScore;
    }
    if (other.Multiple != 0) {
      Multiple = other.Multiple;
    }
    cardList_.Add(other.cardList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          BaseScore = input.ReadInt32();
          break;
        }
        case 16: {
          Multiple = input.ReadInt32();
          break;
        }
        case 26: {
          cardList_.AddEntriesFrom(input, _repeated_cardList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          BaseScore = input.ReadInt32();
          break;
        }
        case 16: {
          Multiple = input.ReadInt32();
          break;
        }
        case 26: {
          cardList_.AddEntriesFrom(ref input, _repeated_cardList_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 出牌参数
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayHandBo : pb::IMessage<PlayHandBo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayHandBo> _parser = new pb::MessageParser<PlayHandBo>(() => new PlayHandBo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayHandBo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CardReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandBo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandBo(PlayHandBo other) : this() {
    pos_ = other.pos_;
    isPass_ = other.isPass_;
    cardList_ = other.cardList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandBo Clone() {
    return new PlayHandBo(this);
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 1;
  private int pos_;
  /// <summary>
  /// 出牌玩家的坐位
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "is_pass" field.</summary>
  public const int IsPassFieldNumber = 2;
  private bool isPass_;
  /// <summary>
  /// 是否不出
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsPass {
    get { return isPass_; }
    set {
      isPass_ = value;
    }
  }

  /// <summary>Field number for the "card_list" field.</summary>
  public const int CardListFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Card> _repeated_cardList_codec
      = pb::FieldCodec.ForMessage(26, global::Card.Parser);
  private readonly pbc::RepeatedField<global::Card> cardList_ = new pbc::RepeatedField<global::Card>();
  /// <summary>
  /// 打出的牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Card> CardList {
    get { return cardList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayHandBo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayHandBo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Pos != other.Pos) return false;
    if (IsPass != other.IsPass) return false;
    if(!cardList_.Equals(other.cardList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Pos != 0) hash ^= Pos.GetHashCode();
    if (IsPass != false) hash ^= IsPass.GetHashCode();
    hash ^= cardList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Pos != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Pos);
    }
    if (IsPass != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsPass);
    }
    cardList_.WriteTo(output, _repeated_cardList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Pos != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Pos);
    }
    if (IsPass != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsPass);
    }
    cardList_.WriteTo(ref output, _repeated_cardList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Pos != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pos);
    }
    if (IsPass != false) {
      size += 1 + 1;
    }
    size += cardList_.CalculateSize(_repeated_cardList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayHandBo other) {
    if (other == null) {
      return;
    }
    if (other.Pos != 0) {
      Pos = other.Pos;
    }
    if (other.IsPass != false) {
      IsPass = other.IsPass;
    }
    cardList_.Add(other.cardList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Pos = input.ReadInt32();
          break;
        }
        case 16: {
          IsPass = input.ReadBool();
          break;
        }
        case 26: {
          cardList_.AddEntriesFrom(input, _repeated_cardList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Pos = input.ReadInt32();
          break;
        }
        case 16: {
          IsPass = input.ReadBool();
          break;
        }
        case 26: {
          cardList_.AddEntriesFrom(ref input, _repeated_cardList_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 出牌响应
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayHandResponse : pb::IMessage<PlayHandResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayHandResponse> _parser = new pb::MessageParser<PlayHandResponse>(() => new PlayHandResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayHandResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CardReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandResponse(PlayHandResponse other) : this() {
    lastPos_ = other.lastPos_;
    isPass_ = other.isPass_;
    pendCards_ = other.pendCards_.Clone();
    monsterPos_ = other.monsterPos_;
    isCover_ = other.isCover_;
    isEnd_ = other.isEnd_;
    multiple_ = other.multiple_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayHandResponse Clone() {
    return new PlayHandResponse(this);
  }

  /// <summary>Field number for the "last_pos" field.</summary>
  public const int LastPosFieldNumber = 1;
  private int lastPos_;
  /// <summary>
  /// 上次请求的玩家的坐位
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LastPos {
    get { return lastPos_; }
    set {
      lastPos_ = value;
    }
  }

  /// <summary>Field number for the "is_pass" field.</summary>
  public const int IsPassFieldNumber = 2;
  private bool isPass_;
  /// <summary>
  /// 上次请求的玩家是否不出
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsPass {
    get { return isPass_; }
    set {
      isPass_ = value;
    }
  }

  /// <summary>Field number for the "pend_cards" field.</summary>
  public const int PendCardsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Card> _repeated_pendCards_codec
      = pb::FieldCodec.ForMessage(26, global::Card.Parser);
  private readonly pbc::RepeatedField<global::Card> pendCards_ = new pbc::RepeatedField<global::Card>();
  /// <summary>
  /// 打出的牌
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Card> PendCards {
    get { return pendCards_; }
  }

  /// <summary>Field number for the "monster_pos" field.</summary>
  public const int MonsterPosFieldNumber = 4;
  private int monsterPos_;
  /// <summary>
  /// 本轮出牌中，打出的牌为最大的玩家的坐位
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MonsterPos {
    get { return monsterPos_; }
    set {
      monsterPos_ = value;
    }
  }

  /// <summary>Field number for the "is_cover" field.</summary>
  public const int IsCoverFieldNumber = 5;
  private bool isCover_;
  /// <summary>
  /// 本次出牌是否压死上家
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsCover {
    get { return isCover_; }
    set {
      isCover_ = value;
    }
  }

  /// <summary>Field number for the "is_end" field.</summary>
  public const int IsEndFieldNumber = 6;
  private bool isEnd_;
  /// <summary>
  /// 游戏是否已经结束
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsEnd {
    get { return isEnd_; }
    set {
      isEnd_ = value;
    }
  }

  /// <summary>Field number for the "multiple" field.</summary>
  public const int MultipleFieldNumber = 7;
  private int multiple_;
  /// <summary>
  /// 最新的倍数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Multiple {
    get { return multiple_; }
    set {
      multiple_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayHandResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayHandResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LastPos != other.LastPos) return false;
    if (IsPass != other.IsPass) return false;
    if(!pendCards_.Equals(other.pendCards_)) return false;
    if (MonsterPos != other.MonsterPos) return false;
    if (IsCover != other.IsCover) return false;
    if (IsEnd != other.IsEnd) return false;
    if (Multiple != other.Multiple) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LastPos != 0) hash ^= LastPos.GetHashCode();
    if (IsPass != false) hash ^= IsPass.GetHashCode();
    hash ^= pendCards_.GetHashCode();
    if (MonsterPos != 0) hash ^= MonsterPos.GetHashCode();
    if (IsCover != false) hash ^= IsCover.GetHashCode();
    if (IsEnd != false) hash ^= IsEnd.GetHashCode();
    if (Multiple != 0) hash ^= Multiple.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (LastPos != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(LastPos);
    }
    if (IsPass != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsPass);
    }
    pendCards_.WriteTo(output, _repeated_pendCards_codec);
    if (MonsterPos != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MonsterPos);
    }
    if (IsCover != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsCover);
    }
    if (IsEnd != false) {
      output.WriteRawTag(48);
      output.WriteBool(IsEnd);
    }
    if (Multiple != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Multiple);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (LastPos != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(LastPos);
    }
    if (IsPass != false) {
      output.WriteRawTag(16);
      output.WriteBool(IsPass);
    }
    pendCards_.WriteTo(ref output, _repeated_pendCards_codec);
    if (MonsterPos != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(MonsterPos);
    }
    if (IsCover != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsCover);
    }
    if (IsEnd != false) {
      output.WriteRawTag(48);
      output.WriteBool(IsEnd);
    }
    if (Multiple != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Multiple);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LastPos != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastPos);
    }
    if (IsPass != false) {
      size += 1 + 1;
    }
    size += pendCards_.CalculateSize(_repeated_pendCards_codec);
    if (MonsterPos != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonsterPos);
    }
    if (IsCover != false) {
      size += 1 + 1;
    }
    if (IsEnd != false) {
      size += 1 + 1;
    }
    if (Multiple != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Multiple);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayHandResponse other) {
    if (other == null) {
      return;
    }
    if (other.LastPos != 0) {
      LastPos = other.LastPos;
    }
    if (other.IsPass != false) {
      IsPass = other.IsPass;
    }
    pendCards_.Add(other.pendCards_);
    if (other.MonsterPos != 0) {
      MonsterPos = other.MonsterPos;
    }
    if (other.IsCover != false) {
      IsCover = other.IsCover;
    }
    if (other.IsEnd != false) {
      IsEnd = other.IsEnd;
    }
    if (other.Multiple != 0) {
      Multiple = other.Multiple;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          LastPos = input.ReadInt32();
          break;
        }
        case 16: {
          IsPass = input.ReadBool();
          break;
        }
        case 26: {
          pendCards_.AddEntriesFrom(input, _repeated_pendCards_codec);
          break;
        }
        case 32: {
          MonsterPos = input.ReadInt32();
          break;
        }
        case 40: {
          IsCover = input.ReadBool();
          break;
        }
        case 48: {
          IsEnd = input.ReadBool();
          break;
        }
        case 56: {
          Multiple = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          LastPos = input.ReadInt32();
          break;
        }
        case 16: {
          IsPass = input.ReadBool();
          break;
        }
        case 26: {
          pendCards_.AddEntriesFrom(ref input, _repeated_pendCards_codec);
          break;
        }
        case 32: {
          MonsterPos = input.ReadInt32();
          break;
        }
        case 40: {
          IsCover = input.ReadBool();
          break;
        }
        case 48: {
          IsEnd = input.ReadBool();
          break;
        }
        case 56: {
          Multiple = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
