// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/ResultEntity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/ResultEntity.proto</summary>
public static partial class ResultEntityReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/ResultEntity.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResultEntityReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chhwcm90by9SZXN1bHRFbnRpdHkucHJvdG8iGwoBUhIWCgRjb2RlGAEgASgO",
          "MgguQ21kQ29kZSKLAQoITG9naW5SZXMSFgoEY29kZRgBIAEoDjIILkNtZENv",
          "ZGUSDwoHdXNlcl9pZBgCIAEoBRIQCgh1c2VybmFtZRgDIAEoCRIOCgZnZW5k",
          "ZXIYBCABKAUSDQoFbW9uZXkYBSABKAUSEQoJd2luX2NvdW50GAYgASgFEhIK",
          "Cmxvc2VfY291bnQYByABKAUqvQEKB0NtZENvZGUSCwoHU3VjY2VzcxAAEggK",
          "BEZhaWwQARIPCgtTZXJ2ZXJFcnJvchACEhAKDEFjY291bnRFeGlzdBADEhMK",
          "D0FjY291bnROb3RFeGlzdBAEEhEKDVBhc3N3b3JkRXJyb3IQBRIQCgxTbXND",
          "b2RlRXJyb3IQBhISCg5Nb2JpbGVOb3RCbGFuaxAHEhQKEFBhc3N3b3JkTm90",
          "QmxhbmsQCBIUChBBY2NvdW50VGVybWluYXRlEAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CmdCode), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::R), global::R.Parser, new[]{ "Code" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoginRes), global::LoginRes.Parser, new[]{ "Code", "UserId", "Username", "Gender", "Money", "WinCount", "LoseCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum CmdCode {
  /// <summary>
  /// 请求成功
  /// </summary>
  [pbr::OriginalName("Success")] Success = 0,
  /// <summary>
  /// 请求失败
  /// </summary>
  [pbr::OriginalName("Fail")] Fail = 1,
  /// <summary>
  /// 服务器异常
  /// </summary>
  [pbr::OriginalName("ServerError")] ServerError = 2,
  /// <summary>
  /// 账号已存在
  /// </summary>
  [pbr::OriginalName("AccountExist")] AccountExist = 3,
  /// <summary>
  /// 账号不存在
  /// </summary>
  [pbr::OriginalName("AccountNotExist")] AccountNotExist = 4,
  /// <summary>
  /// 账号或密码错误
  /// </summary>
  [pbr::OriginalName("PasswordError")] PasswordError = 5,
  /// <summary>
  /// 短信验证码错误
  /// </summary>
  [pbr::OriginalName("SmsCodeError")] SmsCodeError = 6,
  /// <summary>
  /// 手机号不能为空
  /// </summary>
  [pbr::OriginalName("MobileNotBlank")] MobileNotBlank = 7,
  /// <summary>
  /// 密码不能为空
  /// </summary>
  [pbr::OriginalName("PasswordNotBlank")] PasswordNotBlank = 8,
  /// <summary>
  /// 账号被封禁
  /// </summary>
  [pbr::OriginalName("AccountTerminate")] AccountTerminate = 9,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class R : pb::IMessage<R>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<R> _parser = new pb::MessageParser<R>(() => new R());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<R> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResultEntityReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public R() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public R(R other) : this() {
    code_ = other.code_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public R Clone() {
    return new R(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private global::CmdCode code_ = global::CmdCode.Success;
  /// <summary>
  /// 请求结果
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CmdCode Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as R);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(R other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Code != global::CmdCode.Success) hash ^= Code.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Code != global::CmdCode.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Code);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Code != global::CmdCode.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Code);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Code != global::CmdCode.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(R other) {
    if (other == null) {
      return;
    }
    if (other.Code != global::CmdCode.Success) {
      Code = other.Code;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Code = (global::CmdCode) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Code = (global::CmdCode) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 登录成功返回的数据
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LoginRes : pb::IMessage<LoginRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoginRes> _parser = new pb::MessageParser<LoginRes>(() => new LoginRes());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoginRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResultEntityReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginRes(LoginRes other) : this() {
    code_ = other.code_;
    userId_ = other.userId_;
    username_ = other.username_;
    gender_ = other.gender_;
    money_ = other.money_;
    winCount_ = other.winCount_;
    loseCount_ = other.loseCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoginRes Clone() {
    return new LoginRes(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private global::CmdCode code_ = global::CmdCode.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CmdCode Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "user_id" field.</summary>
  public const int UserIdFieldNumber = 2;
  private int userId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UserId {
    get { return userId_; }
    set {
      userId_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 3;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gender" field.</summary>
  public const int GenderFieldNumber = 4;
  private int gender_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gender {
    get { return gender_; }
    set {
      gender_ = value;
    }
  }

  /// <summary>Field number for the "money" field.</summary>
  public const int MoneyFieldNumber = 5;
  private int money_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Money {
    get { return money_; }
    set {
      money_ = value;
    }
  }

  /// <summary>Field number for the "win_count" field.</summary>
  public const int WinCountFieldNumber = 6;
  private int winCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WinCount {
    get { return winCount_; }
    set {
      winCount_ = value;
    }
  }

  /// <summary>Field number for the "lose_count" field.</summary>
  public const int LoseCountFieldNumber = 7;
  private int loseCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LoseCount {
    get { return loseCount_; }
    set {
      loseCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoginRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoginRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (UserId != other.UserId) return false;
    if (Username != other.Username) return false;
    if (Gender != other.Gender) return false;
    if (Money != other.Money) return false;
    if (WinCount != other.WinCount) return false;
    if (LoseCount != other.LoseCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Code != global::CmdCode.Success) hash ^= Code.GetHashCode();
    if (UserId != 0) hash ^= UserId.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Gender != 0) hash ^= Gender.GetHashCode();
    if (Money != 0) hash ^= Money.GetHashCode();
    if (WinCount != 0) hash ^= WinCount.GetHashCode();
    if (LoseCount != 0) hash ^= LoseCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Code != global::CmdCode.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Code);
    }
    if (UserId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(UserId);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Username);
    }
    if (Gender != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gender);
    }
    if (Money != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Money);
    }
    if (WinCount != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WinCount);
    }
    if (LoseCount != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LoseCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Code != global::CmdCode.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Code);
    }
    if (UserId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(UserId);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Username);
    }
    if (Gender != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gender);
    }
    if (Money != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Money);
    }
    if (WinCount != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WinCount);
    }
    if (LoseCount != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LoseCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Code != global::CmdCode.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
    }
    if (UserId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserId);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Gender != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
    }
    if (Money != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Money);
    }
    if (WinCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WinCount);
    }
    if (LoseCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoseCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoginRes other) {
    if (other == null) {
      return;
    }
    if (other.Code != global::CmdCode.Success) {
      Code = other.Code;
    }
    if (other.UserId != 0) {
      UserId = other.UserId;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Gender != 0) {
      Gender = other.Gender;
    }
    if (other.Money != 0) {
      Money = other.Money;
    }
    if (other.WinCount != 0) {
      WinCount = other.WinCount;
    }
    if (other.LoseCount != 0) {
      LoseCount = other.LoseCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Code = (global::CmdCode) input.ReadEnum();
          break;
        }
        case 16: {
          UserId = input.ReadInt32();
          break;
        }
        case 26: {
          Username = input.ReadString();
          break;
        }
        case 32: {
          Gender = input.ReadInt32();
          break;
        }
        case 40: {
          Money = input.ReadInt32();
          break;
        }
        case 48: {
          WinCount = input.ReadInt32();
          break;
        }
        case 56: {
          LoseCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Code = (global::CmdCode) input.ReadEnum();
          break;
        }
        case 16: {
          UserId = input.ReadInt32();
          break;
        }
        case 26: {
          Username = input.ReadString();
          break;
        }
        case 32: {
          Gender = input.ReadInt32();
          break;
        }
        case 40: {
          Money = input.ReadInt32();
          break;
        }
        case 48: {
          WinCount = input.ReadInt32();
          break;
        }
        case 56: {
          LoseCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
